/*
 * This source file was generated by the Gradle 'init' task
 */
package dsa;

import dsa.utils.LinkedList.LinkedList;

public class App {
  

    public static void main(String[] args) {
        LinkedList list = new LinkedList();
        list.unshift(20);
        list.shift();
        System.out.println(list);
    }
}
