/*
 * This source file was generated by the Gradle 'init' task
 */
package dsa;

import dsa.utils.LinkedList.LinkedList;

public class App {
  

    public static void main(String[] args) {
        LinkedList list = new LinkedList();
        list.insert(20);
        list.insert(50);
        list.insert(100);
        list.insert(60);
        System.out.println(list);
        list.unshift(99);
        System.out.println(list);
        list.shift();
        System.out.println(list);
        
    }
}
